name: quote_gallery
description: "A new Flutter project."
publish_to:
environment:
  sdk: ^3.9.2
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  firebase_analytics: ^12.0.4
  firebase_crashlytics: ^5.0.4
  provider: ^6.1.5+1
  cloud_firestore: ^6.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true

