name: quote_gallery
description: "A new Flutter project."
publish_to:
environment:
  sdk: ^3.5.0
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^4.3.0
  firebase_auth: ^6.1.3
  firebase_analytics: ^12.1.0
  firebase_crashlytics: ^5.0.6
  provider: ^6.1.5+1
  cloud_firestore: ^6.1.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true

